#!/usr/bin/env python3
"""Generate tokens.css from tokens.json (stdlib only). Re-run after any token change.

    python3 replica/design/build_tokens.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def ref(value, colors):
    # "{accent}" -> "var(--color-accent)"
    return re.sub(r"\{([a-z0-9-]+)\}",
                  lambda m: "var(--color-%s)" % m.group(1) if m.group(1) in colors else m.group(0), value)


def px(v):
    return v if isinstance(v, str) else "%dpx" % v


def main():
    with open(os.path.join(HERE, "tokens.json"), encoding="utf-8") as fh:
        t = json.load(fh)
    colors = t["color"]
    out = ["/* Generated by build_tokens.py from tokens.json. Do not edit by hand. */", ":root {"]
    for k, v in colors.items():
        out.append("  --color-%s: %s;" % (k, v))
    for k, v in t["gradient"].items():
        out.append("  --gradient-%s: %s;" % (k, ref(v, colors)))
    out.append("  --font-sans: %s;" % t["font"]["sans"])
    out.append("  --font-mono: %s;" % t["font"]["mono"])
    out.append("  --scale: 1;")
    for k, v in t["type"].items():
        if k.startswith("_"):
            continue
        out.append("  --text-%s: calc(%dpx * var(--scale));" % (k, v["size"]))
        out.append("  --leading-%s: calc(%dpx * var(--scale));" % (k, v["line"]))
        out.append("  --weight-%s: %d;" % (k, v["weight"]))
    for i, v in enumerate(t["space"]):
        out.append("  --space-%d: %dpx;" % (i, v))
    for k, v in t["radius"].items():
        out.append("  --radius-%s: %s;" % (k, px(v)))
    for k, v in t["shadow"].items():
        out.append("  --shadow-%s: %s;" % (k, ref(v, colors)))
    for k, v in t["motion"].items():
        if not k.startswith("_"):
            out.append("  --motion-%s: %s;" % (k, v))
    lay = t["layout"]
    out.append("  --rail-w: %dpx;" % lay["rail"]["desktop"])
    out.append("  --page-pad: %dpx;" % lay["page-pad"]["desktop"])
    out.append("  --nav-item: %dpx;" % lay["nav-item"]["desktop"])
    out.append("  --hero-min-h: %dpx;" % lay["hero-min-h"]["desktop"])
    out.append("  --grid-min-card: %dpx;" % lay["grid"]["min-card"])
    out.append("  --grid-gap: %dpx;" % lay["grid"]["gap"])
    out.append("  --control-h: %dpx;" % lay["control-h"]["toolbar"])
    out.append("  --control-h-player: %dpx;" % lay["control-h"]["player"])
    for k, v in lay["z"].items():
        out.append("  --z-%s: %d;" % (k, v))
    out.append("}")
    out.append("html.tv {\n  --scale: 1.3;\n  --rail-w: %dpx;\n  --page-pad: %dpx;\n  --nav-item: %dpx;\n  --hero-min-h: %dpx;\n}"
               % (lay["rail"]["tv"], lay["page-pad"]["tv"], lay["nav-item"]["tv"], lay["hero-min-h"]["tv"]))
    out.append("@media (max-width: %dpx) {\n  :root {\n    --rail-w: %dpx;\n    --page-pad: %dpx;\n    --nav-item: %dpx;\n    --hero-min-h: auto;\n  }\n}"
               % (lay["breakpoints"]["mobile"], lay["rail"]["mobile"], lay["page-pad"]["mobile"], lay["nav-item"]["mobile"]))
    out.append("@media (prefers-reduced-motion: reduce) {\n  :root {\n    --motion-fast: 0ms;\n    --motion-base: 0ms;\n    --motion-slow: 0ms;\n    --motion-fade: 0ms;\n  }\n}")
    with open(os.path.join(HERE, "tokens.css"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote tokens.css (%d colours)" % len(colors))


if __name__ == "__main__":
    main()
