#!/usr/bin/env python3
"""Weekly playlist refresh: re-fetch sources, health-check, prune dead channels.

Designed to run in CI (GitHub Actions), where the runner has unrestricted
network access — so unlike a restricted sandbox it can verify ``http://``
streams as well as ``https://``.

Steps:
  1. Merge the existing source pool (playlists/india.m3u) with fresh pulls from
     iptv-org (India + Hindi/Tamil/Telugu/Bengali/Malayalam), deduped by URL.
  2. Probe every stream and split into active (HTTPS) / active (HTTP) / dead.
  3. Rewrite the playlists, the check report, and the STB channel database.

Run from the repo root:  python scripts/refresh.py
"""

from __future__ import annotations

import datetime as dt
import os
import subprocess
import sys
from urllib.parse import urlparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools", "m3u"))

import m3u  # noqa: E402
from m3u.checker import check_playlist  # noqa: E402

PLAYLISTS = os.path.join(ROOT, "playlists")
SOURCE = os.path.join(PLAYLISTS, "india.m3u")

IPTV_ORG = "https://iptv-org.github.io/iptv"
SOURCES = [
    ("India", f"{IPTV_ORG}/countries/in.m3u"),
    ("Hindi", f"{IPTV_ORG}/languages/hin.m3u"),
    ("Tamil", f"{IPTV_ORG}/languages/tam.m3u"),
    ("Telugu", f"{IPTV_ORG}/languages/tel.m3u"),
    ("Bengali", f"{IPTV_ORG}/languages/ben.m3u"),
    ("Malayalam", f"{IPTV_ORG}/languages/mal.m3u"),
]


def norm(url: str):
    p = urlparse(url)
    return (p.scheme, p.netloc.lower(), p.path)


def fetch(url: str) -> "m3u.Playlist | None":
    import requests

    try:
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        return m3u.parse(resp.text)
    except Exception as exc:  # noqa: BLE001 - a flaky source must not abort refresh
        print(f"  ! failed to fetch {url}: {type(exc).__name__}")
        return None


def build_source_pool() -> "m3u.Playlist":
    base = m3u.parse_file(SOURCE) if os.path.exists(SOURCE) else m3u.Playlist()
    header = base.attributes or {
        "x-tvg-url": "https://raw.githubusercontent.com/StrangeDrVN/epg/public/guide.xml.gz"
    }
    pool = m3u.Playlist(attributes=header)
    seen = set()

    def add(pl):
        added = 0
        for t in pl:
            k = norm(t.path)
            if k not in seen:
                seen.add(k)
                pool.tracks.append(t)
                added += 1
        return added

    print(f"Existing source pool: {add(base)} channels")
    for name, url in SOURCES:
        pl = fetch(url)
        if pl is not None:
            print(f"  + {name}: {len(pl)} fetched, {add(pl)} new")
    print(f"Combined unique source: {len(pool)} channels")
    return pool


def write_report(counts: dict, stamp: str) -> None:
    path = os.path.join(PLAYLISTS, "CHECK_REPORT.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# India playlist — link check report\n\n"
            f"_Last refreshed automatically: **{stamp}**_\n\n"
            "Generated by the weekly `refresh` GitHub Action. Each stream is "
            "fetched and, for HLS endpoints, verified to return a valid "
            "`#EXTM3U` manifest.\n\n"
            "> **Point-in-time snapshot.** Live IPTV streams flap; the list is "
            "re-verified every week.\n\n"
            "## Sources\n\n"
            "Hand-curated list plus the [iptv-org](https://github.com/iptv-org/iptv) "
            "India (`countries/in`) and Hindi, Tamil, Telugu, Bengali & Malayalam "
            "(`languages/*`) collections, deduplicated by URL.\n\n"
            "## Results\n\n"
            "| Bucket | Count | File |\n"
            "|--------|-------|------|\n"
            f"| ✅ Active — HTTPS (browser + player safe) | {counts['https']} | `india-active.m3u` |\n"
            f"| ✅ Active — HTTP (native players only) | {counts['http']} | `india-active-http.m3u` |\n"
            f"| ❌ Dead / unreachable | {counts['dead']} | — |\n"
            f"| Source pool (all) | {counts['total']} | `india.m3u` |\n\n"
            "`india-active.m3u` powers the web set-top box (HTTPS only, so it is "
            "safe to play from the `https://` GitHub Pages site). `http://` "
            "streams cannot play on the HTTPS page (mixed content) — use "
            "`india-active-http.m3u` in a native player like VLC.\n\n"
            "## Notes on dead links\n\n"
            "Most failures are genuine `404`/`403`. Some `403`s are "
            "**geo-blocking** — channels that reject non-India IPs — so they may "
            "still play for you locally.\n"
        )


def main() -> int:
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pool = build_source_pool()
    header = pool.attributes

    print("\nProbing all streams…")
    results = check_playlist(pool, timeout=10, workers=40)

    active_https = m3u.Playlist(attributes=header)
    active_http = m3u.Playlist(attributes=header)
    dead = 0
    for r in results:
        if r.ok:
            (active_https if urlparse(r.track.path).scheme == "https" else active_http).tracks.append(r.track)
        else:
            dead += 1

    counts = {
        "https": len(active_https),
        "http": len(active_http),
        "dead": dead,
        "total": len(pool),
    }
    print(f"\nActive HTTPS: {counts['https']}   Active HTTP: {counts['http']}   "
          f"Dead: {counts['dead']}   Source: {counts['total']}")

    # write playlists
    pool.write_file(SOURCE)
    active_https.write_file(os.path.join(PLAYLISTS, "india-active.m3u"))
    active_http.write_file(os.path.join(PLAYLISTS, "india-active-http.m3u"))
    # remove the obsolete pre-CI bucket if present
    obsolete = os.path.join(PLAYLISTS, "india-unverifiable-http.m3u")
    if os.path.exists(obsolete):
        os.remove(obsolete)

    write_report(counts, stamp)

    # regenerate the STB channel database (reads india-active.m3u)
    subprocess.run([sys.executable, os.path.join(ROOT, "webstb", "build.py")], check=True)

    print("\nRefresh complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
