#!/usr/bin/env python3
"""Weekly playlist refresh: re-fetch sources, health-check, prune dead channels.

Designed to run in CI (GitHub Actions), where the runner has unrestricted
network access — so unlike a restricted sandbox it can verify ``http://``
streams as well as ``https://``.

Steps:
  1. Merge the existing source pool (playlists/india.m3u) with fresh pulls from
     iptv-org (India + Hindi/Tamil/Telugu/Bengali/Malayalam), deduped by URL.
  2. Probe every stream and split into active (HTTPS) / active (HTTP) / dead.
  3. Rewrite the playlists, the check report, and the STB channel database.

Run from the repo root:  python scripts/refresh.py
"""

from __future__ import annotations

import datetime as dt
import os
import subprocess
import sys
from urllib.parse import urlparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools", "m3u"))

import m3u  # noqa: E402
from m3u.checker import check_playlist  # noqa: E402

sys.path.insert(0, os.path.join(ROOT, "webstb"))
from build import dedupe  # noqa: E402  (name-dedupe shared with the STB build)

PLAYLISTS = os.path.join(ROOT, "playlists")
SOURCE = os.path.join(PLAYLISTS, "india.m3u")

IPTV_ORG = "https://iptv-org.github.io/iptv"
SOURCES = [
    ("India", f"{IPTV_ORG}/countries/in.m3u"),
    ("Hindi", f"{IPTV_ORG}/languages/hin.m3u"),
    ("Tamil", f"{IPTV_ORG}/languages/tam.m3u"),
    ("Telugu", f"{IPTV_ORG}/languages/tel.m3u"),
    ("Bengali", f"{IPTV_ORG}/languages/ben.m3u"),
    ("Malayalam", f"{IPTV_ORG}/languages/mal.m3u"),
    ("Kannada", f"{IPTV_ORG}/languages/kan.m3u"),
    ("Marathi", f"{IPTV_ORG}/languages/mar.m3u"),
    ("Punjabi", f"{IPTV_ORG}/languages/pan.m3u"),
    ("Gujarati", f"{IPTV_ORG}/languages/guj.m3u"),
    ("Odia", f"{IPTV_ORG}/languages/ori.m3u"),
    ("Assamese", f"{IPTV_ORG}/languages/asm.m3u"),
    ("Bhojpuri", f"{IPTV_ORG}/languages/bho.m3u"),
]

# Failures that mean "reachable server, our IP refused" — usually geo-blocking.
# Such channels typically work from within India even though CI (US) can't reach
# them, so we keep them in a separate india-geo list rather than discarding.
GEO_REASONS = ("403", "401", "451")


def norm(url: str):
    p = urlparse(url)
    return (p.scheme, p.netloc.lower(), p.path)


def fetch(url: str) -> "m3u.Playlist | None":
    import requests

    try:
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        return m3u.parse(resp.text)
    except Exception as exc:  # noqa: BLE001 - a flaky source must not abort refresh
        print(f"  ! failed to fetch {url}: {type(exc).__name__}")
        return None


def build_source_pool() -> "m3u.Playlist":
    base = m3u.parse_file(SOURCE) if os.path.exists(SOURCE) else m3u.Playlist()
    header = base.attributes or {
        "x-tvg-url": "https://raw.githubusercontent.com/StrangeDrVN/epg/public/guide.xml.gz"
    }
    pool = m3u.Playlist(attributes=header)
    seen = set()

    def add(pl):
        added = 0
        for t in pl:
            k = norm(t.path)
            if k not in seen:
                seen.add(k)
                pool.tracks.append(t)
                added += 1
        return added

    # URL (host+path) -> language, so the STB can offer a language filter.
    # "India" is a country feed, not a language; every other source is labelled
    # with its language. Regional feeds are pulled after Hindi so a channel that
    # appears in both ends up tagged with its regional language.
    import json as _json
    import re as _re

    langmap = {}

    def _urlkey(u):
        m = _re.match(r"https?://([^/]+)(/[^?\s]*)", u or "")
        return f"{m.group(1).lower()}{m.group(2)}" if m else (u or "")

    print(f"Existing source pool: {add(base)} channels")
    for name, url in SOURCES:
        pl = fetch(url)
        if pl is not None:
            print(f"  + {name}: {len(pl)} fetched, {add(pl)} new")
            if name != "India":
                for t in pl:
                    langmap[_urlkey(t.path)] = name
    print(f"Combined unique source: {len(pool)} channels")

    with open(os.path.join(PLAYLISTS, "lang-map.json"), "w", encoding="utf-8") as fh:
        _json.dump(langmap, fh, ensure_ascii=False, separators=(",", ":"))
    print(f"Language map: {len(langmap)} URL→language entries")
    return pool


def write_report(counts: dict, stamp: str) -> None:
    path = os.path.join(PLAYLISTS, "CHECK_REPORT.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# India playlist — link check report\n\n"
            f"_Last refreshed automatically: **{stamp}**_\n\n"
            "Generated by the weekly `refresh` GitHub Action. Each stream is "
            "fetched and, for HLS endpoints, verified to return a valid "
            "`#EXTM3U` manifest.\n\n"
            "> **Point-in-time snapshot.** Live IPTV streams flap; the list is "
            "re-verified every week.\n\n"
            "## Sources\n\n"
            "Hand-curated list plus the [iptv-org](https://github.com/iptv-org/iptv) "
            "India (`countries/in`) and Hindi, Tamil, Telugu, Bengali & Malayalam "
            "(`languages/*`) collections, deduplicated by URL.\n\n"
            "## Results\n\n"
            "| Bucket | Count | File |\n"
            "|--------|-------|------|\n"
            f"| ✅ Active — HTTPS (reachable) | {counts['https']} | `india-active.m3u` |\n"
            f"| 🌐 Browser-playable (CORS-verified) — powers the web app | {counts['web']} | `india-web.m3u` |\n"
            f"| ✅ Active — HTTP (native players only) | {counts['http']} | `india-active-http.m3u` |\n"
            f"| 🇮🇳 Geo-blocked — likely works from India | {counts['geo']} | `india-geo.m3u` |\n"
            f"| ❌ Dead / unreachable | {counts['dead']} | — |\n"
            f"| Source pool (all) | {counts['total']} | `india.m3u` |\n\n"
            "`india-web.m3u` powers the web set-top box — it is the HTTPS subset "
            "whose manifest, variant and first segment all return CORS headers, "
            "so every channel actually plays in a browser (no \"NO SIGNAL — "
            "unavailable in browser\"). `india-active.m3u` is the full reachable "
            "HTTPS list; some of those lack CORS and only play in a native player "
            "like VLC. `http://` streams can't play on the HTTPS page (mixed "
            "content) — use `india-active-http.m3u` in VLC.\n\n"
            "`india-geo.m3u` holds channels that returned `403`/`401` from the "
            "US-based CI runner — they reject non-India IPs, so they usually "
            "**work from an Indian connection** even though they can't be verified "
            "here.\n\n"
            "## Notes on dead links\n\n"
            "Most remaining failures are genuine `404`s or network errors.\n"
        )


CORS_ORIGIN = "https://gnaidu05.github.io"


def _acao(headers) -> bool:
    return any(k.lower() == "access-control-allow-origin" for k in headers)


def _first_uri(text: str, base: str):
    from urllib.parse import urljoin
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        return urljoin(base, line)
    return None


def _playable(url: str) -> bool:
    """True when a stream plays in a browser: CORS present on the manifest, the
    chosen variant, AND the first media segment (hls.js fetches all three)."""
    import requests

    h = {"Origin": CORS_ORIGIN, "Range": "bytes=0-4000"}
    try:
        r = requests.get(url, headers=h, timeout=12)
        if r.status_code not in (200, 206) or not _acao(r.headers):
            return False
        body = r.text
        if "#EXT-X-STREAM-INF" in body:
            var = _first_uri(body, r.url)
            if not var:
                return False
            r2 = requests.get(var, headers=h, timeout=12)
            if r2.status_code not in (200, 206) or not _acao(r2.headers):
                return False
            media, mbase = r2.text, r2.url
        else:
            media, mbase = body, r.url
        seg = _first_uri(media, mbase)
        if not seg:
            return True  # live edge with no segment listed yet — assume ok
        r3 = requests.get(seg, headers={"Origin": CORS_ORIGIN, "Range": "bytes=0-1"},
                          timeout=12, stream=True)
        ok = r3.status_code in (200, 206) and _acao(r3.headers)
        r3.close()
        return ok
    except Exception:  # noqa: BLE001
        return False


def browser_playable(tracks, workers=40):
    """Keep only tracks that are CORS-playable end to end. Two passes so a
    transient timeout doesn't wrongly drop a good channel."""
    import concurrent.futures as cf

    good = set()
    for _ in range(2):
        todo = [t for t in tracks if t.path not in good]
        if not todo:
            break
        with cf.ThreadPoolExecutor(max_workers=workers) as ex:
            for t, ok in zip(todo, ex.map(lambda x: _playable(x.path), todo)):
                if ok:
                    good.add(t.path)
    return [t for t in tracks if t.path in good]


def main() -> int:
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pool = build_source_pool()
    header = pool.attributes

    print("\nProbing all streams…")
    results = check_playlist(pool, timeout=10, workers=40)

    active_https = m3u.Playlist(attributes=header)
    active_http = m3u.Playlist(attributes=header)
    geo = m3u.Playlist(attributes=header)
    dead = 0
    for r in results:
        if r.ok:
            (active_https if urlparse(r.track.path).scheme == "https" else active_http).tracks.append(r.track)
        elif any(g in r.reason for g in GEO_REASONS):
            geo.tracks.append(r.track)
        else:
            dead += 1

    # Collapse HD/SD simulcasts and multi-source copies of the same channel, so
    # players (and the STB) show one entry per channel. Prefers the HD variant.
    active_https.tracks = dedupe(active_https.tracks)
    active_http.tracks = dedupe(active_http.tracks)
    geo.tracks = dedupe(geo.tracks)

    # Browser-playable subset powers the web STB (CORS-verified end to end), so
    # channels that would show "NO SIGNAL — unavailable in browser" are excluded
    # from the app while staying in india-active.m3u for native players.
    print("\nProbing browser playability (CORS)…")
    web = m3u.Playlist(attributes=header)
    web.tracks = browser_playable(active_https.tracks)

    counts = {
        "https": len(active_https),
        "web": len(web),
        "http": len(active_http),
        "geo": len(geo),
        "dead": dead,
        "total": len(pool),
    }
    print(f"\nActive HTTPS: {counts['https']}   Browser-playable: {counts['web']}   "
          f"Active HTTP: {counts['http']}   Geo: {counts['geo']}   "
          f"Dead: {counts['dead']}   Source: {counts['total']}")

    # write playlists
    pool.write_file(SOURCE)
    active_https.write_file(os.path.join(PLAYLISTS, "india-active.m3u"))
    web.write_file(os.path.join(PLAYLISTS, "india-web.m3u"))
    active_http.write_file(os.path.join(PLAYLISTS, "india-active-http.m3u"))
    geo.write_file(os.path.join(PLAYLISTS, "india-geo.m3u"))
    # remove the obsolete pre-CI bucket if present
    obsolete = os.path.join(PLAYLISTS, "india-unverifiable-http.m3u")
    if os.path.exists(obsolete):
        os.remove(obsolete)

    write_report(counts, stamp)

    # regenerate the STB channel database (reads india-active.m3u)
    subprocess.run([sys.executable, os.path.join(ROOT, "webstb", "build.py")], check=True)

    print("\nRefresh complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
