#!/usr/bin/env python3
"""Regenerate webstb/channels.js from the active playlist.

Run from the repo root after refreshing playlists/india-active.m3u:

    python webstb/build.py

It reads playlists/india-active.m3u using the bundled m3u library and writes
the channel database (name, url, logo, group, tvg-id) that the set-top box UI
loads at boot.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "tools", "m3u"))

import m3u  # noqa: E402

PLAYLIST = os.path.join(ROOT, "playlists", "india-active.m3u")
OUT = os.path.join(HERE, "channels.js")


def main() -> int:
    pl = m3u.parse_file(PLAYLIST)
    channels = []
    for i, track in enumerate(pl, start=1):
        attrs = track.attributes
        channels.append(
            {
                "num": i,
                "name": track.title or attrs.get("tvg-name") or f"Channel {i}",
                "url": track.path,
                "logo": attrs.get("tvg-logo", ""),
                "group": attrs.get("group-title", "") or "General",
                "tvgId": attrs.get("tvg-id", ""),
            }
        )

    data = {"epg": pl.attributes.get("x-tvg-url", ""), "channels": channels}
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by build.py from playlists/india-active.m3u\n")
        handle.write("window.STB_DATA = ")
        json.dump(data, handle, ensure_ascii=False, separators=(",", ":"))
        handle.write(";\n")

    with_logo = sum(1 for c in channels if c["logo"])
    print(f"Wrote {len(channels)} channels ({with_logo} with logos) to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
